Preserve data 🎉 🚀 ✔️
Nizamuddin4493/school_library_in_ruby_opp pull request #6
Opened 2022-10-12 19:58 UTC by Nizamuddin4493

# Preserve data 🎉 🚀 ✔️ 

- Store data in files.
- Run a program using the command line.
- On exit app saves all the data (books, people, and rentals) into JSON files.
- On startup, the app loads all data from files.

2022-10-12 20:36 UTC, GzimAsani requested changes
### Hello    @Nizamuddin4493  and @Aquinasmoriasi       :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your setting up jsons file, they work well +1:  
 
 ## Required Changes 

- [ ] Check the comment below :arrow_double_down: 






 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-12 20:36 UTC, GzimAsani commented on app.rb
> +      s_struct = Struct.new(name: student.name, id: student.id, className: student.class, parent_permission: student.parent_permission, age: student.age)
- [ ] It is throwing an error here when I am trying to create a new person kindly update it
![image](https://user-images.githubusercontent.com/62705947/195442268-1b49c797-01ee-4b6c-a7df-7120c35d07f3.png)

2022-10-12 20:36 UTC, GzimAsani commented on persons.json
> +["{\"json_class\":\"OpenStruct\",\"t\":{\"name\":\"Pierre Jardim\",\"id\":901,\"className\":\"Student\",\"parent_permission\":{\"parent_permission\":false},\"age\":19}}", "{\"json_class\":\"OpenStruc
- [ ] If the persons.json file is empty the app crashes, kindly update it with something similar to 
```ruby
    return [] unless File.exists?("people.json")
```

![image](https://user-images.githubusercontent.com/62705947/195442510-429b0449-4c88-4bc9-a3d9-1ee60fa28d20.png)

2022-10-13 11:36 UTC, gemmen29 approved these changes
Hi @Nizamuddin4493, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-13 11:41 UTC, Aquinasmoriasi commented
THank you.

2022-10-13 11:41 UTC, merged